### ISSUE TITLE
Feedback behauviour

### ISSUE THREAD

**Issue by dinism** [ndunand/moodle-qtype_multinumerical#14]
I set a question like this:
![imagem](https://user-images.githubusercontent.com/14828021/212479657-82f4aa61-1d0b-4e74-ad4f-0af77f8722fa.png)
After I saved the question. When i came to edit it, some text of the feedback is missing!
![imagem](https://user-images.githubusercontent.com/14828021/212479802-45522048-f7b0-4d2e-bf24-98ad89e7daea.png)
I tried several times and i NOTED that changing the signal < (less) for > (greater) ALL is OK, but it's NOT what wanted.
![imagem](https://user-images.githubusercontent.com/14828021/212479968-f13cdc01-2c43-4fd4-9d33-36e16780ce3e.png)

**Comment by NicoAlexH** [comment]
Hello, 
thanks for reporting ! The feedback text validation was a bit too strict, this should be fixed once this PR is merged : https://github.com/NicoAlexH/moodle-qtype_multinumerical/commit/b0ff47e037ac6158f7eccc8326cbc0ff2235cc9c

**Comment by NicoAlexH** [comment]
Fixed by #15
