### ISSUE TITLE
Misaligned?

### ISSUE THREAD

**Issue by dinism** [ndunand/moodle-qtype_multinumerical#16]
When previewing question:
![image](https://user-images.githubusercontent.com/14828021/212679046-653c2404-3fc9-4548-99b1-16c10528c17b.png)

**Comment by ndunand** [comment]
@NicoAlexH could this be fixed by using a simple non-breaking space?

**Comment by NicoAlexH** [comment]
@ndunand The issue originates from this line: https://github.com/ndunand/moodle-qtype_multinumerical/blob/master/renderer.php#L71 

HTML entities such as nbsp are not parsed, so I would suggest to simply remove the whitespace before the colon; besides it seems to be more correct, punctuation-wise

https://www.sussex.ac.uk/informatics/punctuation/colonandsemi/colon#:~:text=But%20first%20please%20note%20the,preceded%20by%20a%20white%20space;

https://english.stackexchange.com/questions/67394/spaces-around-a-colon

I added a commit to fix this in my last PR.

**Comment by ndunand** [comment]
ok, thanks for the quick fix!
